apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: backend0
  namespace: default
spec:
  type: state.azure.cosmosdb
  version: v1
  metadata:
  - name: url
    value: {{ cosmos_url }}
  - name: masterKey
    secretKeyRef:
      name: cosmosKey
      key: cosmosKey  
  - name: database
    value: {{ cosmos_db_name }}
  - name: collection
    value: {{ cosmos_collection_name_0 }}
auth:
  secretStore: azurekeyvault
scopes:
- tmtest
- backend

---

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: backend1
  namespace: default
spec:
  type: state.azure.cosmosdb
  version: v1
  metadata:
  - name: url
    value: {{ cosmos_url }}
  - name: masterKey
    secretKeyRef:
      name: cosmosKey
      key: cosmosKey  
  - name: database
    value: {{ cosmos_db_name }}
  - name: collection
    value: {{ cosmos_collection_name_1 }}
auth:
  secretStore: azurekeyvault
scopes:
- tmtest
- backend

