apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: servicebus
  namespace: default
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: connectionString
    secretKeyRef:
      name: serviceBusConnStr
      key: serviceBusConnStr
auth:
  secretStore: azurekeyvault

---

apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: backend-sub
spec:
  topic: backend
  route: /pubsubReceive
  pubsubname: servicebus
scopes:
- backend
