name: cicd
env:
  BUILD_NUMBER: v0.1.0-beta.${{ github.run_number }}

on:
  push:
    branches:
      - main

jobs:
  build_backend:
    runs-on: ubuntu-latest
    steps:

    - name: git checkout
      uses: actions/checkout@v2

    - name: connect to acr
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: build and push container image
      run: |
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/backend:$BUILD_NUMBER
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/backend:$BUILD_NUMBER
      working-directory: ./apps/backend

  build_frontend:
    runs-on: ubuntu-latest
    steps:

    - name: git checkout
      uses: actions/checkout@v2

    - name: connect to acr
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: build and push container image
      run: |
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:$BUILD_NUMBER
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:$BUILD_NUMBER
      working-directory: ./apps/frontend